[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
devrupt = "CDqBjq2XPTdCzuzQnk5eMmRUPt1tkc2J7GKEnNANtdQv"

[programs.devnet]
devrupt = "CDqBjq2XPTdCzuzQnk5eMmRUPt1tkc2J7GKEnNANtdQv"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
test-sbt-devnet = "ANCHOR_PROVIDER_URL=https://api.devnet.solana.com yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/sbt-devnet-test.ts"
